// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Chapter documents */
interface ChapterDocumentData {
    /**
     * Chapter Title field in *Chapter*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: chapter.chapter_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    chapter_title: prismicT.TitleField;
    /**
     * Chapter Number field in *Chapter*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: chapter.chapter_number
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    chapter_number: prismicT.NumberField;
    /**
     * Chapter Hero field in *Chapter*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: chapter.chapter_hero
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    chapter_hero: prismicT.ImageField<never>;
    /**
     * Chapter Day field in *Chapter*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: chapter.chapter_day
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    chapter_day: prismicT.DateField;
    /**
     * Slice zone field in *Chapter*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: chapter.body[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    body: prismicT.SliceZone<ChapterDocumentDataBodySlice>;
}
/**
 * Primary content in Chapter → Slice zone → `quote` → Primary
 *
 */
interface ChapterDocumentDataBodyQuoteSlicePrimary {
    /**
     * Quote_Content field in *Chapter → Slice zone → `quote` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: chapter.body[].quote.primary.quote_content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    quote_content: prismicT.RichTextField;
    /**
     * quote_attribution field in *Chapter → Slice zone → `quote` → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: chapter.body[].quote.primary.quote_attribution
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    quote_attribution: prismicT.KeyTextField;
    /**
     * Quote Citation field in *Chapter → Slice zone → `quote` → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: chapter.body[].quote.primary.quote_citation
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    quote_citation: prismicT.RelationField<"citation">;
}
export type ChapterDocumentDataBodyQuoteSlice = prismicT.Slice<"quote", Simplify<ChapterDocumentDataBodyQuoteSlicePrimary>, never>;
/**
 * Primary content in Chapter → Slice zone → `content` → Primary
 *
 */
interface ChapterDocumentDataBodyContentSlicePrimary {
    /**
     * Content field in *Chapter → Slice zone → `content` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: chapter.body[].content.primary.slice_content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    slice_content: prismicT.RichTextField;
}
export type ChapterDocumentDataBodyContentSlice = prismicT.Slice<"content", Simplify<ChapterDocumentDataBodyContentSlicePrimary>, never>;
/**
 * Primary content in Chapter → Slice zone → `heading` → Primary
 *
 */
interface ChapterDocumentDataBodyHeadingSlicePrimary {
    /**
     * Content field in *Chapter → Slice zone → `heading` → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: chapter.body[].heading.primary.heading_content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    heading_content: prismicT.TitleField;
}
export type ChapterDocumentDataBodyHeadingSlice = prismicT.Slice<"heading", Simplify<ChapterDocumentDataBodyHeadingSlicePrimary>, never>;
/**
 * Primary content in Chapter → Slice zone → `audio_clip` → Primary
 *
 */
interface ChapterDocumentDataBodyAudioClipSlicePrimary {
    /**
     * Title field in *Chapter → Slice zone → `audio_clip` → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: chapter.body[].audio_clip.primary.audio_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    audio_title: prismicT.TitleField;
    /**
     * Audio Clip field in *Chapter → Slice zone → `audio_clip` → Primary*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: chapter.body[].audio_clip.primary.audio_clip
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    audio_clip: prismicT.LinkToMediaField;
    /**
     * Description field in *Chapter → Slice zone → `audio_clip` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: chapter.body[].audio_clip.primary.audio_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    audio_description: prismicT.RichTextField;
}
export type ChapterDocumentDataBodyAudioClipSlice = prismicT.Slice<"audio_clip", Simplify<ChapterDocumentDataBodyAudioClipSlicePrimary>, never>;
/**
 * Slice for *Chapter → Slice zone*
 *
 */
type ChapterDocumentDataBodySlice = ChapterDocumentDataBodyQuoteSlice | ChapterDocumentDataBodyContentSlice | ChapterDocumentDataBodyHeadingSlice | ChapterDocumentDataBodyAudioClipSlice;
/**
 * Chapter document from Prismic
 *
 * - **API ID**: `chapter`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ChapterDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ChapterDocumentData>, "chapter", Lang>;
/** Content for Citation documents */
interface CitationDocumentData {
    /**
     * Citation Body field in *Citation*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: citation.citation_body
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    citation_body: prismicT.RichTextField;
}
/**
 * Citation document from Prismic
 *
 * - **API ID**: `citation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CitationDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<CitationDocumentData>, "citation", Lang>;
/** Content for Day Summary documents */
interface DaySummaryDocumentData {
    /**
     * date field in *Day Summary*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: day_summary.day_summary_date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    day_summary_date: prismicT.DateField;
    /**
     * content field in *Day Summary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: day_summary.day_summary_content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    day_summary_content: prismicT.RichTextField;
}
/**
 * Day Summary document from Prismic
 *
 * - **API ID**: `day_summary`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DaySummaryDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<DaySummaryDocumentData>, "day_summary", Lang>;
/** Content for Foreward documents */
interface ForewardDocumentData {
    /**
     * Content field in *Foreward*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: foreward.foreward_content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    foreward_content: prismicT.RichTextField;
}
/**
 * Foreward document from Prismic
 *
 * - **API ID**: `foreward`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ForewardDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ForewardDocumentData>, "foreward", Lang>;
/** Content for Introduction documents */
interface IntroductionDocumentData {
    /**
     * Content field in *Introduction*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: introduction.introduction_content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    introduction_content: prismicT.RichTextField;
}
/**
 * Introduction document from Prismic
 *
 * - **API ID**: `introduction`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IntroductionDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<IntroductionDocumentData>, "introduction", Lang>;
/** Content for Person documents */
interface PersonDocumentData {
    /**
     * Name field in *Person*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: person.person_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    person_name: prismicT.TitleField;
    /**
     * Image field in *Person*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: person.person_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    person_image: prismicT.ImageField<never>;
    /**
     * Biography field in *Person*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: person.person_biography
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    person_biography: prismicT.RichTextField;
}
/**
 * Person document from Prismic
 *
 * - **API ID**: `person`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PersonDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PersonDocumentData>, "person", Lang>;
/** Content for Place documents */
interface PlaceDocumentData {
    /**
     * Name field in *Place*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: place.place_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    place_name: prismicT.TitleField;
    /**
     * Image field in *Place*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: place.place_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    place_image: prismicT.ImageField<never>;
    /**
     * Description field in *Place*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: place.place_description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    place_description: prismicT.RichTextField;
}
/**
 * Place document from Prismic
 *
 * - **API ID**: `place`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PlaceDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PlaceDocumentData>, "place", Lang>;
/** Content for Preface documents */
interface PrefaceDocumentData {
    /**
     * Content field in *Preface*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: preface.preface_content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    preface_content: prismicT.RichTextField;
}
/**
 * Preface document from Prismic
 *
 * - **API ID**: `preface`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrefaceDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PrefaceDocumentData>, "preface", Lang>;
/** Content for Tour Location documents */
interface TourLocationDocumentData {
    /**
     * Tour Sort Order field in *Tour Location*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: tour_location.tour_sort_order
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    tour_sort_order: prismicT.KeyTextField;
    /**
     * tour blub field in *Tour Location*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: tour_location.tour_blub
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    tour_blub: prismicT.RichTextField;
    /**
     * Title field in *Tour Location*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: tour_location.tour_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    tour_title: prismicT.TitleField;
    /**
     * location field in *Tour Location*
     *
     * - **Field Type**: GeoPoint
     * - **Placeholder**: *None*
     * - **API ID Path**: tour_location.tour_coords
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/geopoint
     *
     */
    tour_coords: prismicT.GeoPointField;
    /**
     * Main Image field in *Tour Location*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: tour_location.tour_main_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    tour_main_image: prismicT.ImageField<never>;
    /**
     * Content field in *Tour Location*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: tour_location.tour_content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    tour_content: prismicT.RichTextField;
}
/**
 * Tour Location document from Prismic
 *
 * - **API ID**: `tour_location`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TourLocationDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<TourLocationDocumentData>, "tour_location", Lang>;
export type AllDocumentTypes = ChapterDocument | CitationDocument | DaySummaryDocument | ForewardDocument | IntroductionDocument | PersonDocument | PlaceDocument | PrefaceDocument | TourLocationDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ChapterDocumentData, ChapterDocumentDataBodyQuoteSlicePrimary, ChapterDocumentDataBodyQuoteSlice, ChapterDocumentDataBodyContentSlicePrimary, ChapterDocumentDataBodyContentSlice, ChapterDocumentDataBodyHeadingSlicePrimary, ChapterDocumentDataBodyHeadingSlice, ChapterDocumentDataBodyAudioClipSlicePrimary, ChapterDocumentDataBodyAudioClipSlice, ChapterDocumentDataBodySlice, ChapterDocument, CitationDocumentData, CitationDocument, DaySummaryDocumentData, DaySummaryDocument, ForewardDocumentData, ForewardDocument, IntroductionDocumentData, IntroductionDocument, PersonDocumentData, PersonDocument, PlaceDocumentData, PlaceDocument, PrefaceDocumentData, PrefaceDocument, TourLocationDocumentData, TourLocationDocument, AllDocumentTypes };
    }
}
