name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install
        run: yarn install --production=false

      - name: Build & Export
        run: |
          yarn build
          yarn export
        env:
          PRISMIC_API_TOKEN: ${{ secrets.PRISMIC_ACCESS_TOKEN }}
          PRISMIC_REPOSITORY_NAME: ${{ secrets.PRISMIC_REPO_NAME }}

      # Next.js relies on a `_next` folder
      # https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
      # GitHub Pages relies on /404.html
      - name: Support GitHub Pages
        run: |
          touch out/.nojekyll
          mv out/404/index.html out/404.html && rm -r out/404

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: out
