name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          yarn install --production=false
          yarn run build
          touch out/.nojekyll
        env:
          ACCESS_TOKEN: ${{ secrets.PRISMIC_ACCESS_TOKEN }}
          REPO_NAME: ${{ secrets.PRISMIC_REPO_NAME }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: out
