name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Yarn install
        uses: ./.github/actions/yarn-install

      - name: lint
        run: yarn lint
