name: Lint

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: yarn install
        run: yarn install --production=false
      - name: eslint
        uses: icrawl/action-eslint@v1

